# Generated by Django 5.1 on 2024-08-19 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employeeName", models.CharField(max_length=255)),
                ("background", models.TextField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "performance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "contractStatus",
                    models.CharField(
                        choices=[
                            ("P", "Parttime"),
                            ("F", "Fulltime"),
                            ("R", "Resigned"),
                        ],
                        default="F",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentName", models.CharField(max_length=255)),
                (
                    "education",
                    models.CharField(
                        choices=[("U", "Undergraduate"), ("G", "Graduate")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("university", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "grades",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "contractStatus",
                    models.CharField(
                        choices=[("S", "Success"), ("F", "Failed")],
                        default="F",
                        max_length=1,
                    ),
                ),
                ("contractTime", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("lastUpdate", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CID",
            fields=[
                ("cid", models.CharField(max_length=255)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="student.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="students",
            field=models.ManyToManyField(to="student.student"),
        ),
    ]
