# Generated by Django 5.1 on 2024-08-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="students",
            field=models.ManyToManyField(related_name="teachers", to="student.student"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["university", "grades"], name="StudentInfo_univers_0b08e4_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="student",
            table="StudentInformation",
        ),
    ]
