# Generated by Django 5.1 on 2024-08-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_employee_students_and_more"),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO StudentInformation (studentName, education, contractStatus)
            VALUES ('小明', 'U', 'F')
        """, """
            DELETE FROM StudentInformation
            WHERE studentName = '小明'
        """)
    ]
